source "http://rubygems.org"

# Declare your gem's dependencies in blacklight-hierarchy-facets.gemspec.
gemspec

# Declare any dependencies that are still in development here instead of in
# your gemspec. These might include edge Rails or gems from your path or
# Git. Remember to move these dependencies to your gemspec before releasing
# your gem to rubygems.org.

# sprockets 2.11.0 required by blacklight test app generated by engine_cart 
# If we don't specify it here, we'll end up with a conflict with version in Gemfile.lock
gem 'sprockets', '2.11.0'

# sass 3.2.0 required by blacklight test app generated by engine_cart 
# If we don't specify it here, we'll end up with a conflict with version in Gemfile.lock
gem 'sass', '~> 3.2.0'
gem 'bootstrap-sass', ">= 3.1.1.1"

# load local rails test instance Gemfile (engine cart adds this automagically)
#file = File.expand_path("Gemfile", ENV['ENGINE_CART_DESTINATION'] || ENV['RAILS_ROOT'] || File.expand_path("../spec/internal", __FILE__))
#if File.exists?(file)
#  puts "Loading #{file} ..." if $DEBUG # `ruby -d` or `bundle -v`
#  instance_eval File.read(file)
#end

if File.exists?('spec/test_app_templates/Gemfile.extra')
  eval File.read('spec/test_app_templates/Gemfile.extra'), nil, 'spec/test_app_templates/Gemfile.extra'
end
